// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjabsgftnzhulvzaxjlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqYWJzZ2Z0bnpodWx2emF4amxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3Mjk1NTQsImV4cCI6MjA1MTMwNTU1NH0.PGvpn-j-R2HqSIL7W_5Jk37pfZ5xhKiMdY7b1pbmsEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);